[tool.poetry]
name = "demo"
version = "0.1.0"
description = ""
authors = ["Helge <helge.krueger@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
bovine = "^0.1.4"
behave = "^1.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
